"""The published-tree guarantees (v1.2 Phase 2 — PUB-01/02/04/05).

These tests define "publishable". They run in three places on purpose — the local suite,
the CI ``site-integrity`` job (every push/PR), and the deploy workflow's pre-publish gate —
so the thing that ships is the thing that was tested, by the same code path
(``publish.assemble_site``), with no bash re-implementation anywhere.
"""

from __future__ import annotations

import pathlib
import re

import pytest

from newsletters.publish import _CORPUS_LAYOUT, assemble_site

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

_HREF_OR_SRC = re.compile(r'(?:href|src)="([^"]*)"')
_FONT_URL = re.compile(r"url\('([^']*\.woff2)'\)")
_MARKER = "generated by newsletters.render; do not hand-edit"
_BASE_PATH = "/newsletters/"


def _assemble(tmp_path: pathlib.Path, name: str = "site") -> pathlib.Path:
    out = tmp_path / name
    assemble_site(out, base_path=_BASE_PATH, repo_root=REPO_ROOT)
    return out


# --------------------------------------------------------------------------- #
# assemble_site — the assembly function itself
# --------------------------------------------------------------------------- #


def test_assemble_composes_three_corpora_and_chrome(tmp_path: pathlib.Path) -> None:
    out = _assemble(tmp_path)
    # rev1 fronts the site at the root; the other records sit alongside.
    assert (out / "index.html").is_file()
    assert (out / "library.html").is_file()
    assert (out / "work" / "library.html").is_file()
    assert (out / "module" / "library.html").is_file()
    assert (out / "module" / "report-module-a.html").is_file(), (
        "the module report is the page that 404'd on the LIVE site — it must be in the tree"
    )
    # Assembly chrome.
    assert (out / ".nojekyll").is_file()
    assert (out / "404.html").is_file()


def test_assemble_is_byte_stable(tmp_path: pathlib.Path) -> None:
    """Two assemblies of the same committed tree are byte-identical (determinism)."""
    a = _assemble(tmp_path, "a")
    b = _assemble(tmp_path, "b")
    files_a = sorted(p.relative_to(a) for p in a.rglob("*") if p.is_file())
    files_b = sorted(p.relative_to(b) for p in b.rglob("*") if p.is_file())
    assert files_a == files_b, "the two assemblies produced different file sets"
    for rel in files_a:
        assert (a / rel).read_bytes() == (b / rel).read_bytes(), f"{rel} differs across assemblies"


def test_assemble_copies_committed_bytes_verbatim(tmp_path: pathlib.Path) -> None:
    """What was reviewed is what publishes — corpus files are byte-copies, never re-rendered."""
    out = _assemble(tmp_path)
    for src, dest in _CORPUS_LAYOUT:
        src_dir = REPO_ROOT / src
        dest_dir = out if dest == "." else out / dest
        for f in sorted(p for p in src_dir.rglob("*") if p.is_file()):
            rel = f.relative_to(src_dir)
            assert (dest_dir / rel).read_bytes() == f.read_bytes(), (
                f"{dest}/{rel} is not a byte-copy of the committed corpus file"
            )


def test_assemble_fails_loud_on_missing_corpus(tmp_path: pathlib.Path) -> None:
    """A missing corpus aborts BEFORE any file is written — no partial site, ever."""
    fake_root = tmp_path / "repo"
    (fake_root / "content/rev1/site").mkdir(parents=True)  # rev1 only; work+module absent
    out = tmp_path / "out"
    with pytest.raises(FileNotFoundError, match="work"):
        assemble_site(out, repo_root=fake_root)
    assert not out.exists(), "assemble wrote a partial tree despite a missing corpus"


def test_assemble_refuses_foreign_out_dir(tmp_path: pathlib.Path) -> None:
    """A non-empty out dir that is not a previous assembly is refused, never clobbered."""
    precious = tmp_path / "precious"
    precious.mkdir()
    (precious / "keep.txt").write_text("not yours")
    with pytest.raises(FileExistsError):
        assemble_site(precious, repo_root=REPO_ROOT)
    assert (precious / "keep.txt").read_text() == "not yours"
    # …but a PREVIOUS assembly (recognized by its .nojekyll marker) reassembles cleanly.
    out = _assemble(tmp_path)
    assemble_site(out, base_path=_BASE_PATH, repo_root=REPO_ROOT)


# --------------------------------------------------------------------------- #
# Guarantee (a) — no dead link in the ASSEMBLED tree (PUB-03's resolver of record)
# --------------------------------------------------------------------------- #


def test_assembled_internal_links_resolve(tmp_path: pathlib.Path) -> None:
    """Every href/src in every assembled page resolves to a real file in the tree.

    This is the test that, run against the tree that was live on 2026-07-03, would have
    caught the ``/module/`` 404 — and it is the resolver of record for the Phase-1
    cross-corpus Records-strip hrefs (``work/…``, ``../…``), which the per-corpus test can
    only shape-check. 404.html is the one deliberate exception to relative links: its
    targets are asserted base-path-absolute and resolved against the tree root.
    """
    out = _assemble(tmp_path)
    checked = 0
    for page in sorted(out.rglob("*.html")):
        text = page.read_text(encoding="utf-8")
        assert 'href="None"' not in text and 'href=""' not in text, f"dead href in {page}"
        for target in _HREF_OR_SRC.findall(text):
            if "://" in target or target.startswith("#") or target.startswith("mailto:"):
                continue
            target = target.split("#", 1)[0]
            if page.name == "404.html":
                assert target.startswith(_BASE_PATH), (
                    f"404.html carries a non-absolute target {target!r} — it must be "
                    "base-path-absolute (it serves at arbitrary depth)"
                )
                resolved = out / target[len(_BASE_PATH) :]
            else:
                resolved = (page.parent / target).resolve()
            assert resolved.is_file(), f"{page.relative_to(out)} links to missing {target!r}"
            checked += 1
    # ~160 internal links at v1.2 open (externals/anchors excluded); the floor guards
    # against a silently-broken extractor, not a shrinking site.
    assert checked > 100, f"only {checked} links checked — extraction looks broken"


# --------------------------------------------------------------------------- #
# Guarantee (b) — no drift: committed corpus == fresh render (rev1 + work; module
# already guarded by tests/test_modulesite.py::test_committed_equals_fresh_build)
# --------------------------------------------------------------------------- #


def _assert_committed_equals_fresh(
    corpus_dir: pathlib.Path,
    fresh_dir: pathlib.Path,
    ledger: pathlib.Path,
    *,
    html_only: bool = False,
) -> None:
    # html_only: the rev1 corpus is the CANONICAL font source — its committed fonts/ are
    # vendored assets that build_site never emits (work/module _emit_fonts copy FROM it),
    # so for rev1 only the renderer-produced *.html are committed==fresh comparable; the
    # fonts' presence/resolvability is guaranteed by test_fonts_referenced_are_present.
    pattern = "*.html" if html_only else "*"
    committed = sorted(p for p in corpus_dir.rglob(pattern) if p.is_file())
    assert committed, f"no committed files under {corpus_dir}"
    for src in committed:
        rel = src.relative_to(corpus_dir)
        built = fresh_dir / rel
        assert built.exists(), f"fresh build is missing committed file {rel}"
        assert built.read_bytes() == src.read_bytes(), (
            f"{rel} differs between the committed corpus and a fresh build — the committed "
            "site has drifted from the renderer; regenerate in the same commit as the change"
        )
    assert ledger.is_file(), f"ledger {ledger} missing"


def test_committed_rev1_equals_fresh_build(tmp_path: pathlib.Path) -> None:
    from newsletters.dogfood import build_site

    ledger = REPO_ROOT / "content/rev1/ids.json"
    before = ledger.read_bytes()
    build_site(tmp_path)
    assert ledger.read_bytes() == before, "fresh rev1 build mutated the committed ledger"
    _assert_committed_equals_fresh(
        REPO_ROOT / "content/rev1/site", tmp_path, ledger, html_only=True
    )


def test_committed_work_equals_fresh_build(tmp_path: pathlib.Path) -> None:
    from newsletters.worksurface import build_work_site

    ledger = REPO_ROOT / "content/work/ids.json"
    before = ledger.read_bytes()
    build_work_site(tmp_path)
    assert ledger.read_bytes() == before, "fresh work build mutated the committed ledger"
    _assert_committed_equals_fresh(REPO_ROOT / "content/work/site", tmp_path, ledger)


# --------------------------------------------------------------------------- #
# Guarantee (c) — fonts referenced == fonts present (and the licenses travel)
# --------------------------------------------------------------------------- #


def test_fonts_referenced_are_present(tmp_path: pathlib.Path) -> None:
    out = _assemble(tmp_path)
    checked = 0
    for page in sorted(out.rglob("*.html")):
        for url in _FONT_URL.findall(page.read_text(encoding="utf-8")):
            resolved = (
                out / url[len(_BASE_PATH) :] if url.startswith(_BASE_PATH) else (page.parent / url).resolve()
            )
            assert resolved.is_file(), f"{page.relative_to(out)} references missing font {url!r}"
            checked += 1
    assert checked > 0, "no font references found — extraction looks broken"
    # The SIL-OFL licenses ship beside every corpus's vendored fonts.
    for fonts_dir in (out / "fonts", out / "work/fonts", out / "module/fonts"):
        ofls = list(fonts_dir.glob("OFL-*.txt"))
        assert len(ofls) == 3, f"{fonts_dir} must carry the three OFL license files, has {ofls}"


# --------------------------------------------------------------------------- #
# Guarantee (d) — every assembled page is renderer output (the generated marker)
# --------------------------------------------------------------------------- #


def test_every_assembled_page_carries_generated_marker(tmp_path: pathlib.Path) -> None:
    out = _assemble(tmp_path)
    pages = sorted(out.rglob("*.html"))
    assert pages, "no pages assembled"
    for page in pages:
        assert _MARKER in page.read_text(encoding="utf-8"), (
            f"{page.relative_to(out)} lacks the generated-by marker — hand-edited or "
            "foreign HTML must never publish"
        )
